// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_gxmqkOo1MBbE7AA4qq9lb7qTZBSVc7E',
    appId: '1:837989483683:web:e86b6700bf99589a426b16',
    messagingSenderId: '837989483683',
    projectId: 'test-thunkable-e8b09',
    authDomain: 'test-thunkable-e8b09.firebaseapp.com',
    databaseURL: 'https://test-thunkable-e8b09-default-rtdb.firebaseio.com',
    storageBucket: 'test-thunkable-e8b09.appspot.com',
    measurementId: 'G-Q0KGKHY076',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAT9AVz2tP2We4Ukgk4wogHfY2SsrRgQo',
    appId: '1:837989483683:android:95665d0ea97a4f58426b16',
    messagingSenderId: '837989483683',
    projectId: 'test-thunkable-e8b09',
    databaseURL: 'https://test-thunkable-e8b09-default-rtdb.firebaseio.com',
    storageBucket: 'test-thunkable-e8b09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0an_X6TMNoi47ImwJskn_8fcfFzHTORA',
    appId: '1:837989483683:ios:07c641e89fc24543426b16',
    messagingSenderId: '837989483683',
    projectId: 'test-thunkable-e8b09',
    databaseURL: 'https://test-thunkable-e8b09-default-rtdb.firebaseio.com',
    storageBucket: 'test-thunkable-e8b09.appspot.com',
    iosClientId: '837989483683-cu52g34fbpcoernahqj72c53jvblksch.apps.googleusercontent.com',
    iosBundleId: 'com.yourdomain.kontrolSuhu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0an_X6TMNoi47ImwJskn_8fcfFzHTORA',
    appId: '1:837989483683:ios:07c641e89fc24543426b16',
    messagingSenderId: '837989483683',
    projectId: 'test-thunkable-e8b09',
    databaseURL: 'https://test-thunkable-e8b09-default-rtdb.firebaseio.com',
    storageBucket: 'test-thunkable-e8b09.appspot.com',
    iosClientId: '837989483683-cu52g34fbpcoernahqj72c53jvblksch.apps.googleusercontent.com',
    iosBundleId: 'com.yourdomain.kontrolSuhu',
  );
}
